(deftheme mccarthy
  "Created 2015-02-16.")

(custom-theme-set-faces
 'mccarthy
 '(bold ((t (:bold t))))
 '(button ((t (:foreground "#3B5998" :underline t))))
 '(header-line ((t (:background "#0087af" :foreground "#f6f7f8"))))
 '(highlight ((t (:background "#CCC"))))
 '(highlight-face ((t (:background "#CCC"))))
 '(hl-line ((t (:underline (:color nil :style nil) :background "#CCC"))))
 '(info-xref ((t (:foreground "#3B5998" :underline t))))
 '(region ((t (:background "#CCC"))))
 '(underline ((nil (:underline t))))
 '(font-lock-builtin-face ((t (:foreground "#2c3140"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#2c5115"))))
 '(font-lock-comment-face ((t (:foreground "#2c5115"))))
 '(font-lock-constant-face ((t (:foreground "#008080"))))
 '(font-lock-doc-face ((t (:foreground "#555"))))
 '(font-lock-doc-string-face ((t (:foreground "#555"))))
 '(font-lock-function-name-face ((t (:foreground "#1b1e2b"))))
 '(font-lock-keyword-face ((t (:foreground "#3B5998"))))
 '(font-lock-negation-char-face ((t (:foreground "#3b5998"))))
 '(font-lock-number-face ((t (:foreground "#5b93fc"))))
 '(font-lock-preprocessor-face ((t (:foreground "#3B5998"))))
 '(font-lock-reference-face ((t (:foreground "#008080"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#E9C"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#E9C"))))
 '(font-lock-string-face ((t (:foreground "#555"))))
 '(font-lock-type-face ((t (:foreground "#2c3140"))))
 '(font-lock-variable-name-face ((t (:foreground "#D14"))))
 '(font-lock-warning-face ((t (:foreground "#3b5998"))))
 '(fringe ((t (:background "#f6f7f8"))))
 '(linum ((t (:background "#EEE"))))
 '(minibuffer-prompt ((t (:foreground "#D14"))))
 '(mode-line ((t (:background "#CCC" :foreground "#555"))))
 '(mode-line-inactive ((t (:background "#999" :foreground "#f6f7f8"))))
 '(cursor ((t (:background "#CCC"))))
 '(text-cursor ((t (:background "#CCC"))))
 '(vertical-border ((t (:foreground "#f6f7f8"))))
 '(show-paren-mismatch ((t (:background "#3b5998" :foreground "#555" :weight bold))))
 '(show-paren-match ((t (:background "#3B5998" :foreground "#555" :weight bold))))
 '(isearch ((t (:background "#0087af" :foreground "#f6f7f8"))))
 '(isearch-fail ((t (:background "#3b5998"))))
 '(lazy-highlight ((t (:background "#2c3140" :foreground "#CCC"))))
 '(default ((t (:background "#f6f7f8" :foreground "#555")))))

(provide-theme 'mccarthy)
